on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TFVERSION }}
      - uses: ministryofjustice/github-actions/code-formatter@v6
        with:
          ignore-files: "lambda/requirements.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
